title: "Rustで始めるVulkan Raytracing"
summary: "rust-gpuとashでレイトレーシングします"
topics: ["Rust", "rustgpu", "Vulkan"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - about
  - rust-gpu-intro
  - run-rasterization
  - vkr-overview
  - vkr-shader
  - run-raytracing
  - add-triangle
