-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sandbox]
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace sandbox

/- [sandbox::main]:
   Source: 'src/main.rs', lines 1:0-1:12 -/
def main : Result Unit :=
  ok ()

/- [sandbox::add]:
   Source: 'src/main.rs', lines 3:0-5:1 -/
def add (a : I32) (b : I32) : Result I32 :=
  a + b

/- [sandbox::fma]:
   Source: 'src/main.rs', lines 7:0-9:1 -/
def fma (a : I32) (b : I32) (c : I32) : Result I32 :=
  do
  let i ← a * b
  i + c

/- [sandbox::Pcg64Si]
   Source: 'src/main.rs', lines 12:0-14:1 -/
structure Pcg64Si where
  state : U64

/- [sandbox::{sandbox::Pcg64Si}::next_u64]:
   Source: 'src/main.rs', lines 17:4-27:5 -/
def Pcg64Si.next_u64 (self : Pcg64Si) : Result (U64 × Pcg64Si) :=
  do
  let i ←
    (↑(core.num.U64.wrapping_mul self.state 6364136223846793005#u64) : Result
      U64)
  let i1 ←
    (↑(core.num.U64.wrapping_add i 1442695040888963407#u64) : Result U64)
  let i2 ← self.state >>> 59#i32
  let i3 ← i2 + 5#u64
  let i4 ← self.state >>> i3
  let i5 ← (↑(i4 ^^^ self.state) : Result U64)
  let word ←
    (↑(core.num.U64.wrapping_mul i5 12605985483714917081#u64) : Result U64)
  let i6 ← word >>> 43#i32
  let i7 ← (↑(i6 ^^^ word) : Result U64)
  ok (i7, { state := i1 })

end sandbox
